ALTER TABLE usuarios
  ADD COLUMN IF NOT EXISTS edad       INT,
  ADD COLUMN IF NOT EXISTS peso_kg    NUMERIC(5,1),
  ADD COLUMN IF NOT EXISTS altura_cm  INT,
  ADD COLUMN IF NOT EXISTS objetivo   TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS plan_ia    JSONB;
